# numpy

In [1]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# nump套件ndarray型態，提供element-wise的操作

In [2]:
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)

[ 3  6  9 12 15]


# ndarrary維度 shape 資料型態

In [3]:
print(type(a_ndarray))
print(a_ndarray.ndim)
print(a_ndarray.shape)
print(a_ndarray.dtype)

<class 'numpy.ndarray'>
1
(5,)
int32


# ndarray的進階操作

In [5]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


# ndarray取值

In [6]:
my_2d_array = np.array([np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])  #第二列資料
print(my_2d_array[:,1])  #第二欄資料
print(my_2d_array[1,1])  #第二列第二航資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


# Ndarrary轉置

In [7]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


# ndarray nan(空值)

In [8]:
nan_array=np.array([56,8,19,14,6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]
